---
- name: Snipe It Clone 
  git:
      repo: git@github.com:PearlThoughts/asset-tracker.git
      dest: /home/ubuntu/environment/asset-tracker
      update: no

- name: Copy file with owner and permissions
  copy:
      src: .env
      dest: /home/ubuntu/environment/asset-tracker/.env
